<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title><?php echo $title; ?></title>
<style>
body {
    font-family: "Times New Roman", serif;
    font-size: 12px;
}
h1, h2 {
    text-align: center;
    margin: 0;
}
hr {
    margin: 10px 0;
}
table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 10px;
}
th, td {
    border: 1px solid #000;
    padding: 5px;
}
th {
    background: #f0f0f0;
}
.text-center {
    text-align: center;
}
.text-right {
    text-align: right;
}
.footer {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    font-size: 10px;
    text-align: center;
}
</style>
</head>

<body>

<h1><?php echo $title; ?></h1>
<h2><?php echo $subtitle; ?></h2>
<p class="text-center">Generated: <?php echo $generated; ?></p>

<hr>

<h3>Hasil Perangkingan Alternatif</h3>

<table>
<thead>
<tr>
    <th width="10%">Rank</th>
    <th>Nama Kampus</th>
    <th width="25%">Skor Akhir</th>
</tr>
</thead>
<tbody>
<?php foreach ($ranking as $r): ?>
<tr>
    <td class="text-center"><?php echo $r['rank']; ?></td>
    <td><?php echo html_escape($r['alternative']); ?></td>
    <td class="text-right"><?php echo number_format($r['score'], 6); ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>

<hr>

<h3>Daftar Kriteria</h3>

<table>
<thead>
<tr>
    <th>Kode</th>
    <th>Nama Kriteria</th>
    <th>Tipe</th>
    <th>Bobot</th>
</tr>
</thead>
<tbody>
<?php foreach ($criterias as $c): ?>
<tr>
    <td class="text-center"><?php echo html_escape($c->code); ?></td>
    <td><?php echo html_escape($c->name); ?></td>
    <td class="text-center"><?php echo strtoupper($c->type); ?></td>
    <td class="text-center"><?php echo $c->weight; ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>

<div class="footer">
    Laporan SPK – Metode Simple Scoring | Generated by Sistem
</div>

</body>
</html>
